// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHIJFBHzUn47yXxjjH4SkFE31ZHDxSbWc',
    appId: '1:1088748112784:web:7e1aac42f28927d22ec115',
    messagingSenderId: '1088748112784',
    projectId: 'el-karooz',
    authDomain: 'el-karooz.firebaseapp.com',
    storageBucket: 'el-karooz.appspot.com',
    measurementId: 'G-500G5P5EN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS7U80OrdNVmCmqoZfdEPVI9Izlvak16g',
    appId: '1:1088748112784:android:78d99800c1983f8b2ec115',
    messagingSenderId: '1088748112784',
    projectId: 'el-karooz',
    storageBucket: 'el-karooz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZqJRw4YVBO1gcjmeDPC372c_e6zZXbxY',
    appId: '1:1088748112784:ios:b20d1f080ef5594e2ec115',
    messagingSenderId: '1088748112784',
    projectId: 'el-karooz',
    storageBucket: 'el-karooz.appspot.com',
    iosClientId: '1088748112784-b1j556ik7n27qn15hjrkq8ku50ve94sr.apps.googleusercontent.com',
    iosBundleId: 'com.elkarooz.elKarooz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZqJRw4YVBO1gcjmeDPC372c_e6zZXbxY',
    appId: '1:1088748112784:ios:cdaf2184967e07c32ec115',
    messagingSenderId: '1088748112784',
    projectId: 'el-karooz',
    storageBucket: 'el-karooz.appspot.com',
    iosClientId: '1088748112784-5fp9clm04jujs0p74tn4ob02a3kso8tn.apps.googleusercontent.com',
    iosBundleId: 'com.elkarooz.elKarooz.RunnerTests',
  );
}
